services:
  db:
    container_name: swe2db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: swenuser
      POSTGRES_PASSWORD: swenpassword
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    networks:
      - db
    ports:
      - "5432:5432"
networks:
  db:
    driver: bridge
volumes:
  postgres-db:
    driver: local