server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tourplanner
    username: swenuser
    password: swenpassword
  jpa:
    hibernate:
      ddl-auto: update # after db schema change create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true